### ISSUE TITLE
Helm chart does not work for kubernetes 1.16+

### ISSUE THREAD

**Issue by templafymek** [games-on-k8s/docker-factorio#19]
The template in helm chart for the deployment is using old kind and does not work for kubernetes 1.16+.

**Comment by mdonoughe** [comment]
This looks abandoned. This repository is for the Docker images, which haven't updated since February 2019.

The Helm chart is at https://github.com/helm/charts/tree/master/stable/factorio, and will be [delisted from Helm Hub in two months](https://github.com/helm/charts#deprecation-timeline).
