### ISSUE TITLE
Release versions later than 0.15.33

### ISSUE THREAD

**Issue by adamcharnock** [games-on-k8s/docker-factorio#9]
Could you release versions later than ``0.15.33``? I believe we are now up to ``0.15.37``.

**Comment by dendle** [comment]
Yeah this would be great if possible!

**Comment by dendle** [comment]
yay! a new image is being made with the latest version! our prayers have been answered!

**Comment by gtaylor** [comment]
It looks like they're only keeping the latest patchlevel version from each minor release, so I could only publish 0.15.37.

**Comment by adamcharnock** [comment]
Amazing, thanks @gtaylor.

**Comment by dendle** [comment]
yeah thanks @gtaylor!!
